name: Update Notion Statuses

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  notion_update_job:
    runs-on: ubuntu-latest
    name: Update Notion Task
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci

      - name: Update Notion Task
        uses: ./update_notion # Uses an action in the root directory
        id: update_notion
        with:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_TOKEN: ${{ secrets.NOTION_DATABASE_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
